# fly.toml app configuration file generated for dc24-wallet-verifier-hei on 2024-07-17T12:43:10+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'dc24-wallet-verifier-hei'
primary_region = 'ams'

[build]
  dockerfile = '/Dockerfile.jvm'

[env]
  FLY_API_TOKEN = 'fo1_ioweKc5z3fPfoXHHO8nMXyBhIahaTJ_y3JOYGPBWJlo'
  MATTR_CLIENT_ID = 'GAzkUGEWppv9Pxeo7rnVZplIgzmYAuAJ'
  MATTR_CLIENT_SECRET = 'DWzgojQOfTpeQUXjFMbMlDqoBrqLcpid-F8z7uFalb6aMb4t4mliMHAKsAEwgD7M'
  MATTR_DOMAIN = 'karsten-friis-dyttcc.vii.au01.mattr.global'
  MATTR_ISSUER_DID = 'did:web:karsten-friis-dyttcc.vii.au01.mattr.global'
  MATTR_TENANT_URL = 'https://karsten-friis-dyttcc.vii.au01.mattr.global'
  MATTR_VERIFIER_DID = 'did:web:karsten-friis-dyttcc.vii.au01.mattr.global'

[http_service]
  internal_port = 2001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
