# fly.toml app configuration file generated for dc24-verifier on 2024-07-23T12:04:29+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'dc24-verifier'
primary_region = 'ams'

[build]
  dockerfile = '/Dockerfile.jvm'

[http_service]
  internal_port = 2001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[env]
  MATTR_TENANT_URL="hei123"
  MATTR_CLIENT_ID="hei123"
  MATTR_CLIENT_SECRET="hei123"
  MATTR_DOMAIN="hei123"
  MATTR_ISSUER_DID="hei123"
  MATTR_VERIFIER_DID="hei123"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
