spring:
    application:
        name: ansattporten-integration
server:
    port: 2001
    servlet:
        session:
            timeout: 30m
            cookie:
                same-site: Lax
    
logging:
    level:
        root: INFO
