spring:
    application:
        name: ansattporten-integration
    session:
        store-type: none
    security:
        oauth2:
            client:
                registration:
                    testclient:
                        client-name: Logg inn med Ansattporten
                        client-id: dc24_ansattporten_testclient
                        client-secret: ${clientSecret}
                        authorization-grant-type: authorization_code
                        redirect-uri: "{baseUrl}/login/oauth2/code/testclient"
                        scope: openid, profile
                        provider: ansattporten
                provider:
                    ansattporten:
                        issuer-uri: https://test.ansattporten.no
    redis:
        host: localhost
        port: 6379
server:
    port: 2001
    servlet:
        session:
            timeout: 30m

logging:
    level:
        root: INFO