spring:
    application:
        name: ansattporten-integration
    redis:
        host: localhost
        port: 6379
    port: 2001
    servlet:
        session:
            timeout: 30m

logging:
    level:
        root: INFO