spring:
    application:
        name: ansattporten-integration
    session:
        store-type: redis
        redis:
            namespace: ansattporten-integration
            flush-mode: on_save
    data:
        redis:
            password: password
            host: localhost
            port: 6379
server:
    port: 2001
    servlet:
        session:
            timeout: 30m

logging:
    level:
        root: INFO