name: Fly Deploy
on:
  push:
    branches:
      - main    
      - deploy_with_GitHub_Actions
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group    # optional: ensure only one action runs at a time
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Rename env file
        run: |
          if [ -f src/main/resources/.env.example ]; then
            mv src/main/resources/.env.example src/main/resources/.env
            echo ".env file created from .env.example"
          else
            echo ".env.example file not found"
          fi

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build Docker image
        run: |
          docker build -f Dockerfile.jvm -t my-app:latest .
        # env:
        #   MATTR_CLIENT_SECRET: ${{ secrets.MATTR_CLIENT_SECRET }}
        #   MATTR_CLIENT_ID: ${{ secrets.MATTR_CLIENT_ID }}
        #   MATTR_DOMAIN: ${{ secrets.MATTR_DOMAIN }}
        #   MATTR_ISSUER_DID: ${{ secrets.MATTR_ISSUER_DID }}
        #   MATTR_TENANT_URL: ${{ secrets.MATTR_TENANT_URL }}
        #   MATTR_VERIFIER_DID: ${{ secrets.MATTR_VERIFIER_DID }}

      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Log in to Fly.io
        run: flyctl auth docker
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Deploy with Flyctl
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          MATTR_CLIENT_SECRET: ${{ secrets.MATTR_CLIENT_SECRET }}
          MATTR_CLIENT_ID: ${{ secrets.MATTR_CLIENT_ID }}
          MATTR_DOMAIN: ${{ secrets.MATTR_DOMAIN }}
          MATTR_ISSUER_DID: ${{ secrets.MATTR_ISSUER_DID }}
          MATTR_TENANT_URL: ${{ secrets.MATTR_TENANT_URL }}
          MATTR_VERIFIER_DID: ${{ secrets.MATTR_VERIFIER_DID }}
        run: flyctl deploy --remote-only
